
name: 保活验证工作流

on:
  # 自动定时运行（每天 UTC 8:00）
  schedule:
    - cron: "1 5,6,7,8 * * *"  # 北京时间 9:20, 13:20, 23:20
  workflow_dispatch:
jobs:
  validate-baohuo:
    runs-on: ubuntu-latest
    
    steps:
    # 1. 检出代码
    - name: 拉取代码
      uses: actions/checkout@v3

    # 2. 设置 Node.js 环境
    - name: 设置 Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 3. 安装依赖
    - name: 安装依赖
      run: npm install axios

    # 4. 运行验证脚本
    - name: 执行保护货验证
      id: run-script
      run: |
        # 捕获脚本输出（忽略stderr中的进度日志）
        output=$(node baohuo.js 2>&1 | grep -v '=>')  # 过滤掉实时服务器状态行
        echo "脚本原始输出：$output"
        
        # 提取标准化结果
        SUMMARY=$(echo "$output" | grep -oP "通过=\d+_失败=\d+_异常=\d+")
        DETAILS=$(echo "$output" | grep -oP "details=.+")
        
        # 解析统计数字
        PASSED=$(echo "$SUMMARY" | cut -d'_' -f1 | cut -d'=' -f2)
        FAILED=$(echo "$SUMMARY" | cut -d'_' -f2 | cut -d'=' -f2)
        ERRORS=$(echo "$SUMMARY" | cut -d'_' -f3 | cut -d'=' -f2)
        
        # 动态生成通知消息
        if [ "$FAILED" -gt 0 ] || [ "$ERRORS" -gt 0 ]; then
          RESULT="failure"
          MSG="⚠️ 验证异常 (通过:$PASSED 失败:$FAILED 异常:$ERRORS)"
        else
          RESULT="success"
          MSG="✅ 全部通过 ($PASSED个)"
        fi
        
        # 严格输出到GitHub Actions
        echo "result=$RESULT" >> $GITHUB_OUTPUT
        echo "message=$MSG" >> $GITHUB_OUTPUT
        echo "$DETAILS" >> $GITHUB_OUTPUT

    # 5. 微信通知（无论成功/失败都推送）
    - name: 发送微信通知
      env:
        WXP_TOKEN: "AT_8W0HaJDqsTjYPxgsyCdg5xxGU58e7a9q"
        WXP_UID: "UID_pT7ifPmHs5ewHZcNXE9saeXCCopf"
      run: |
        # 解析原始数据中的服务器状态
        RAW_DETAILS='${{ steps.run-script.outputs.details }}'
        SERVER_STATUS=$(echo "$RAW_DETAILS" | jq -r '.[] | "\(.server): \(.status)"' | paste -sd "\n" -)
        
        # 构建通知内容
        CONTENT="保护验证报告：
        ${{ steps.run-script.outputs.message }}
        --------------------------
        服务器状态：
        ${SERVER_STATUS}
        --------------------------
        时间: $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')"
        
        # 发送通知（含换行符处理）
        curl -X POST "https://wxpusher.zjiecode.com/api/send/message" \
          -H "Content-Type: application/json" \
          -d '{
            "appToken": "'"$WXP_TOKEN"'",
            "content": "'"$(echo "$CONTENT" | sed 's/"/\\"/g')"'",
            "contentType": 1,
            "uids": ["'"$WXP_UID"'"]
          }'
