
name: 保活验证工作流

on:
  # 自动定时运行（每天 UTC 8:00）
  schedule:
    - cron: "1 5,6,7,8 * * *"  # 北京时间 9:20, 13:20, 23:20
  workflow_dispatch:
jobs:
  validate-baohuo:
    runs-on: ubuntu-latest
    
    steps:
    # 1. 检出代码
    - name: 拉取代码
      uses: actions/checkout@v3

    # 2. 设置 Node.js 环境
    - name: 设置 Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 3. 安装依赖
    - name: 安装依赖
      run: npm install axios

    # 4. 运行验证脚本
    - name: 执行保护货验证
      id: run-script
      run: |
        output=$(node baohuo.js)
        echo "脚本输出：$output"
        # 提取统计结果（示例输出："通过:9个 失败:1个 异常:1个"）
        stats=$(echo "$output" | grep -oP "通过:\d+个 失败:\d+个 异常:\d+个")
        # 根据结果设置状态
        if echo "$output" | grep -q "失败:0个 异常:0个"; then
          echo "result=success" >> $GITHUB_OUTPUT
          echo "message=✅ 全部通过 ($stats)" >> $GITHUB_OUTPUT
        elif echo "$output" | grep -q "通过:0个"; then
          echo "result=failure" >> $GITHUB_OUTPUT
          echo "message=❌ 全部失败 ($stats)" >> $GITHUB_OUTPUT
        else
          echo "result=partial_failure" >> $GITHUB_OUTPUT
          echo "message=⚠️ 部分通过 ($stats)" >> $GITHUB_OUTPUT
        fi
        echo "details=${output}" >> $GITHUB_OUTPUT

    # 5. 微信通知（无论成功/失败都推送）
    - name: 发送微信通知
      env:
        WXP_TOKEN: "AT_8W0HaJDqsTjYPxgsyCdg5xxGU58e7a9q"
        WXP_UID: "UID_pT7ifPmHs5ewHZcNXE9saeXCCopf"
      run: |
        CURRENT_TIME=$(TZ='Asia/Shanghai' date "+%Y-%m-%d %H:%M:%S CST")
        # 构建更详细的通知内容
        CONTENT="保护验证结果：\n\n${{ steps.run-script.outputs.message }}\n\n详细统计：\n${{ steps.run-script.outputs.details }}\n\n触发时间：$CURRENT_TIME"
        curl -s -X POST \
          "https://wxpusher.zjiecode.com/api/send/message" \
          -H "Content-Type: application/json" \
          -d '{
            "appToken": "'"$WXP_TOKEN"'",
            "content": "'"${CONTENT}"'",
            "contentType": 1,
            "uids": ["'"$WXP_UID"'"]
          }'
